[package]
name = "sorting_in_rust"
version = "0.1.0"
authors = ["Krister Wolfhard <krister.wolfhard@it-designers.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
